sudo: required
services:
  - docker

before_install: 
  - docker build -t hansherrlich/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hansherrlich/docker-react npm run test     
    
